---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - ingresses
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - rollout.example.com
  resources:
  - canaryrollouts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rollout.example.com
  resources:
  - canaryrollouts/finalizers
  verbs:
  - update
- apiGroups:
  - rollout.example.com
  resources:
  - canaryrollouts/status
  verbs:
  - get
  - patch
  - update
